import type { IndexToken } from "./types";

export const mockIndexes: IndexToken[] = [
  {
    id: "zidx-meme",
    name: "Meme Basket",
    symbol: "ZIDX-MEME",
    type: "token",
    description: "Top-performing meme tokens bundled in one index",
    theme: "Meme",
    tvl: 1250000,
    volume24h: 350000,
    performance7d: 12.4,
    performance30d: 28.7,
    composition: [
      { token: "DOGE", percentage: 50 },
      { token: "SHIB", percentage: 50 },
    ],
  },
  {
    id: "zidx-defi",
    name: "DeFi Index",
    symbol: "ZIDX-DEFI",
    type: "token",
    description: "Exposure to decentralized finance protocols",
    theme: "DeFi",
    tvl: 3500000,
    volume24h: 750000,
    performance7d: -3.2,
    performance30d: 5.8,
    composition: [
      { token: "AAVE", percentage: 30 },
      { token: "UNI", percentage: 40 },
      { token: "COMP", percentage: 30 },
    ],
  },
  {
    id: "zidx-blue",
    address: process.env
      .NEXT_PUBLIC_INDEX_TOKEN_ADDRESS_ZIDX_BLUE as `0x${string}`,
    name: "Blue Chip",
    symbol: "ZIDX-BLUE",
    type: "token",
    description: "Major cryptocurrencies with established market presence",
    theme: "Blue-Chip",
    tvl: 8750000,
    volume24h: 1250000,
    performance7d: 2.1,
    performance30d: 12.3,
    composition: [
      { token: "ETH", percentage: 60 },
      { token: "LINK", percentage: 40 },
    ],
  },
  {
    id: "zidx-equal",
    name: "Equal Weight",
    symbol: "ZIDX-EQUAL",
    type: "token",
    description: "Equal allocation across major crypto assets",
    theme: "Blue-Chip",
    tvl: 4250000,
    volume24h: 850000,
    performance7d: 1.8,
    performance30d: 9.5,
    composition: [
      { token: "ETH", percentage: 25 },
      { token: "LINK", percentage: 25 },
      { token: "AAVE", percentage: 25 },
      { token: "UNI", percentage: 25 },
    ],
  },
];
